vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        warplane_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
