name: CI

on:
    push:
    pull_request:

jobs:
    lint:
        name: Docker Lint
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Lint Dockerfile
            uses: hadolint/hadolint-action@master
            with:
                dockerfile: Dockerfile
                ignore: DL3007,DL3018 # Ignore using latest on mlocati/php-extension-installer & version in apk add
    build:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
